version: "{build}"
environment:
  APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG: true
image:
  - Visual Studio 2022
  - Ubuntu2004
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
    - /release-.*/
init:
  - cmd: dotnet --info
  - sh: dotnet --info
build_script:
  - cmd: ./build
  - sh: ./build
test: off
deploy: off
